### ISSUE TITLE
 change the "Generate wallet" button to "Generate/Restore wallet" (using seed phrase)

### ISSUE THREAD

**Issue by lludlow** [MyHush/wallet.myhush.org#2]
gigaho - Today at 6:48 PM
Web wallet request: can you change the "Generate wallet" button to "Generate/Restore wallet" (using seed phrase). this will eliminate confusion for people wanting to view wallet balances, as "Generate" implies the wallet was not already generated.

**Comment by gilardh** [comment]
The button name visible on https://wallet.myhush.org/ is : "Generate Wallet / Login".
![image](https://user-images.githubusercontent.com/39105646/45303909-31d94d00-b517-11e8-831e-8670ab6ff819.png)
If that's okay, we could close that request.
